services:
  frontend:
    build:
      context: ./tg-web-app
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./tg-web-app:/app
      - /app/node_modules
